<div>
<h1>Privacy Policy for Adwis</h1>
<p><strong>Last updated:</strong> March 07, 2025</p>

<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>

<h2>Interpretation and Definitions</h2>

<h3>Interpretation</h3>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

<h3>Definitions</h3>
<p>For the purposes of this Privacy Policy:</p>
<ul>
  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
  <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
  <li><strong>Application</strong> refers to Adwis, the software program provided by the Company.</li>
  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Adwis.</li>
  <li><strong>Country</strong> refers to: Czechia</li>
  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
  <li><strong>Service</strong> refers to the Application.</li>
  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
</ul>

<h2>Collecting and Using Your Personal Data</h2>

<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>

<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>

<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
  <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
  <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
  <li>To manage Your requests: To attend and manage Your requests to Us.</li>
  <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, etc.</li>
  <li>For other purposes: data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
</ul>

<p>We may share Your personal information in the following situations:</p>
<ul>
  <li>With Service Providers: to monitor and analyze the use of our Service, to contact You.</li>
  <li>For business transfers: during negotiations of any merger, sale of assets, financing, or acquisition.</li>
  <li>With Affiliates: We will require those affiliates to honor this Privacy Policy.</li>
  <li>With business partners: to offer You certain products, services or promotions.</li>
  <li>With other users: when You share personal information in public areas.</li>
  <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>

<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary. We will retain and use Your Personal Data to comply with our legal obligations, resolve disputes, and enforce our agreements and policies.</p>

<p>Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or improve the functionality of Our Service.</p>

<h3>Transfer of Your Personal Data</h3>
<p>Your information may be transferred to — and maintained on — computers located outside of Your jurisdiction where data protection laws may differ.</p>

<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

<p>The Company ensures Your data is treated securely and no transfer will take place to an organization or a country unless adequate controls are in place.</p>

<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

<p>Our Service may give You the ability to delete certain information. You may update, amend, or delete Your information at any time by signing in to Your Account or by contacting Us.</p>

<p>However, we may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

<h2>Disclosure of Your Personal Data</h2>

<h3>Business Transactions</h3>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>

<h3>Law enforcement</h3>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data by law or in response to valid requests.</p>

<h3>Other legal requirements</h3>
<p>The Company may disclose Your Personal Data in good faith belief that such action is necessary to:</p>
<ul>
  <li>Comply with a legal obligation</li>
  <li>Protect and defend the rights or property of the Company</li>
  <li>Prevent or investigate possible wrongdoing</li>
  <li>Protect the personal safety of Users</li>
  <li>Protect against legal liability</li>
</ul>

<h2>Security of Your Personal Data</h2>
<p>The security of Your Personal Data is important to Us, but no method of transmission over the Internet is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If You are a parent and aware Your child has provided Us with Personal Data, please contact Us.</p>

<p>If We become aware that We have collected Personal Data from anyone under 13 without verification of parental consent, We take steps to remove that information.</p>

<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites not operated by Us. If You click on a third party link, You will be directed to that site. We advise You to review the Privacy Policy of every site You visit.</p>

<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites.</p>

<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

<p>We will let You know via email and/or a notice on Our Service prior to the change becoming effective and update the "Last updated" date.</p>

<p>You are advised to review this Privacy Policy periodically. Changes are effective when posted on this page.</p>

<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
  <li>By email: <a href="mailto:wannepain@outlook.cz">wannepain@outlook.cz</a></li>
</ul>
</div>
<style>
  h1, h2, h3 {
    margin-top: 1.5rem;
    color: #333;
  }

  p, li {
    line-height: 1.6;
  }

  ul {
    padding-left: 1.2rem;
  }

  a {
    color: #0070f3;
    text-decoration: underline;
  }
  div{
    width: 100%;
    padding: 2.5rem;
  }
</style>